package com.gollum.jammyfurniturecompatibility.client;

import com.gollum.jammyfurniturecompatibility.common.CommonProxyJammyFurnitureZuxelusCompatibility;

public class ClientProxyJammyFurnitureZuxelusCompatibility extends CommonProxyJammyFurnitureZuxelusCompatibility {

}